---
# tasks file for localTerraform
- name: Create Generation Directory
  file:
    path: "{{ bin_directory }}"
    state: directory

- name: Find distribution
  set_fact:
    terraform_os: "{{ 'darwin' if ansible_distribution == 'MacOSX' else 'linux' }}"

- name: Check for existing Terraform binary
  ansible.builtin.stat:
    path: "{{ bin_directory }}/terraform"
  register: terraform_path_check

- name: Download and Unzip Terraform
  ansible.builtin.unarchive:
    src: "{{ terraform_url }}"
    dest: "{{ bin_directory }}"
    mode: 0755
    remote_src: yes
  tags:
    - download_terraform
  when: not terraform_path_check.stat.exists

- name: Set Terraform path
  set_fact:
    bin_directory: "{{ bin_directory }}"
    terraform_path: "{{ bin_directory }}/terraform"
