---
## This Playbook will deploy a Kubernetes Workshop environment with a single bastion node for the workshop proctor, X number of Control Plane Nodes and Y Number of Application Nodes with an optional Load Balancer Node for Z Number of Student Seats
- name: Deploy Kubernetes 101 Workshop
  hosts: localhost
  gather_facts: true
  collections:
    - community.crypto
    - community.general
    - ibm.cloudcollection

  tasks:
    - name: Provision Terraform locally
      include_role:
        name: localTerraform
      tags:
        - local_terraform

    - name: Build infrastructure
      include_role:
        name: ws-kubernetes101
        tasks_from: deploy_with_terraform
      vars:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
      tags:
        - build_infra
    #    - name: Deploy DNS Nodes to support workshop
    #      include_role:
    #        name: createDNSNodes
    #      vars:
    #        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    - name: Template out Zones YAML file
      include_role:
        name: ws-kubernetes101
        tasks_from: template_zones_file
      tags:
        - template_zones_yaml

    - name: Configure DNSNB
      include_role:
        name: dnsnb
      when: dnsnb_provider is defined
      tags:
        - dnsnb

- name: Connect to DNS VSIs and set base global configuration
  hosts: dns_vsi
  collections:
    - ansible.posix
  gather_facts: true
  tasks:
    - name: Configure DNS servers - FirewallD
      include_role:
        name: kenmoini.firewalld
      tags:
        - dns_configuration
        - firewalld
      vars:
        force_restart_of_firewalld: true
        firewalld_services:
          - ssh
          - cockpit
        firewalld_ports:
          - "53/tcp"
          - "53/udp"

    - name: Configure DNS servers - Cockpit
      include_role:
        name: kenmoini.cockpit
      tags:
        - dns_configuration
        - cockpit

    - name: Pull in zones variable
      include_vars:
        file: "{{ tfile_dir }}/zones.yaml"
      tags:
        - dns_configuration
        - zones_configuration

    - name: Configure DNS servers
      include_role:
        name: configureDNSNodes
      tags:
        - dns_configuration
        - dns_daemon_configuration

- name: Connect to new VSIs and set base global configuration
  hosts: ext_workshop_vsi
  collections:
    - ansible.posix
  gather_facts: true
  tasks:
    - name: Configure infrastructure basics
      include_role:
        name: ws-kubernetes101
        tasks_from: global_configuration
      tags:
        - global_configuration

    - name: Set up System DNS vars
      include_role:
        name: setSystemDNS
        tasks_from: template_system_dns_vars.yaml
      with_items: "{{ groups['dns_vsi'] }}"
      tags:
        - set_system_dns

    - name: Set system DNS to deployed servers
      include_role:
        name: setSystemDNS
      when: inventory_hostname not in groups.dns_vsi
      vars:
        system_search_domain: "{{ guid }}.{{ domain }}"
      tags:
        - set_system_dns

- name: Set up Proctor Bastion
  hosts: pb_vsi
  gather_facts: true
  tasks:

    - name: Bootstrap Proctor Bastion
      include_role:
        name: ws-kubernetes101
        tasks_from: bootstrap_proctor_bastion.yaml