---
- name: Tear down Containers 101 Workshop
  hosts: localhost
  gather_facts: false
  collections:
    - ibm.cloudcollection

  tasks:
    - name: Retrieve IBM Cloud cURL API Bearer Token
      uri:
        url: "https://iam.cloud.ibm.com/identity/token"
        method: POST
        body_format: form-urlencoded
        body:
          grant_type: urn:ibm:params:oauth:grant-type:apikey
          apikey: "{{ ibmcloud_api_key }}"
        headers:
          Accept: application/json
      register: curl_api_token

    - name: Remove DNS infrastructure from IBM Cloud
      include_role:
        name: createDNSNodes
        tasks_from: destroy
      vars:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        ibm_api_token: "{{ curl_api_token.json.token_type }} {{ curl_api_token.json.access_token }}"

    - name: Remove infrastructure from IBM Cloud
      include_role:
        name: ws-containers101-tf
        tasks_from: destroy
      vars:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        ibm_api_token: "{{ curl_api_token.json.token_type }} {{ curl_api_token.json.access_token }}"