---
## This Playbook will deploy an OpenShift 4 Workshop environment
- name: Deploy OpenShift 4 Workshop
  hosts: localhost
  gather_facts: true
  collections:
    - community.crypto
    - community.general
    - ibm.cloudcollection

  tasks:
  # Create Proctor Bastion/Boostrap Node in IBM with basic Ansible Modules
  # Configure PB/BSN with Terraform, fcct, jq, oc, openshift-install, and other basics
  # Template over Terraform and other config
  # Deploy Stage 1 Terraform - VPC, Subnets, DNS Nodes
  # Deploy Stage 2 Terraform - OCP 4 Bootstrap Node
  # Deploy Stage 3 Terraform - OCP 4 Cluster Nodes
  # Deploy Stage 4 Terraform - Additional Nodes such as GitLab, Minio, NFS, etc
  # Run additional post-cluster deployment configuration