---
- name: "Template out Student {{ studentNum }} Node {{ node_count }} Cloud Init Config"
  template:
    src: terraform/cloud_inits/ansible_nodes.yaml.j2
    dest: "{{ tfile_dir }}/cloud_inits/student{{ studentNum }}-node-{{ node_count }}.yaml"
  when: recreate_templates|bool
  with_sequence: start=1 end="{{ student_node_count }}" stride=1
  loop_control:
    loop_var: node_count

- name: "Create Workshop Student {{ studentNum }} Node {{ node_count }} Manifest"
  template:
    src: terraform/ansible_nodes.tf.j2
    dest: "{{ tfile_dir }}/student{{ studentNum }}-node-{{ node_count }}.tf"
  with_sequence: start=1 end="{{ student_node_count }}" stride=1
  loop_control:
    loop_var: node_count
