---
# defaults file for createDNSNodes
number_of_dns_nodes: 2

# system_domain is hostname FQDN suffix, eg `ns{{ num }}.{{ system_domain }}`
system_domain: example.com

## dns_daemon options: knot | coredns
dns_daemon: knot

dns_vsi_profile: cx2-2x4
dns_vsi_image: ibm-centos-8-2-minimal-amd64-2
rh_subscription: false

region: us-south
regional_zone: us-south-3
api_endpoint: "https://{{ region }}.iaas.cloud.ibm.com"

dns_port: 53
upstream_dns_server: 1.1.1.1

dns_node_tcp_port_rules:
  - start: 22
    end: 22
    direction: inbound
    remote: 0.0.0.0/0
    name: tcp_dns_SSHIn
  - start: 53
    end: 53
    direction: inbound
    remote: 0.0.0.0/0
    name: tcp_dns_DNSIn
  - start: 9090
    end: 9090
    direction: inbound
    remote: 0.0.0.0/0
    name: tcp_dns_CockpitIn

dns_node_udp_port_rules:
  - start: 53
    end: 53
    direction: inbound
    remote: 0.0.0.0/0
    name: udp_dns_DNSIn
  - start: 9090
    end: 9090
    direction: inbound
    remote: 0.0.0.0/0
    name: udp_dns_CockpitIn

####################################################
## KnotDNS Config

knot_auth_dns: true
knot_resolving_dns: true

knot_auth_dns_port: 54
knot_resolving_dns_port: 53

knot_user: knot
knot_group: knot

# knot_auth_dns_logging options: stdout, stderr, syslog, /path/to/file
knot_auth_dns_logging: syslog
# knot_auth_dns_logging_level options from least to most verbose: critical, error, warning, notice, info, debug
knot_auth_dns_logging_level: info

knot_auth_dns_default_zone_path: /var/lib/knot/zones

# knot_auth_dns_semantic_checks: off || on - Important: Wrap in quotes or else it will be interpreted as a boolean
knot_auth_dns_semantic_checks: "off"

knot_auth_dns_acl_notify_allow_cidr: 10.0.0.0/8
knot_auth_dns_acl_transfer_allow_cidr: 10.0.0.0/8
knot_auth_dns_acl_update_allow_cidr: 10.0.0.0/8

knot_auth_dns_tsigkey_name: tsigkey.
knot_auth_dns_tsigkey_path: /var/lib/knot/dns-tsigkey.yml

knot_resolving_dns_cache_size_mb: 1024
