---
- name: Template over Terraform files
  include_tasks: template_terraform_stage2.yml

- name: Run Terraform
  community.general.terraform:
    project_path: "{{ tfile_dir }}/stage2/"
    state: present
    force_init: true
    binary_path: "{{ terraform_path }}"
    variables:
      ibmcloud_api_key: "{{ ibmcloud_api_key }}"
  register: terraform_stage2_result
  delay: 3
  retries: 3
  until: terraform_stage2_result is not failed
  tags:
    - run_terraform_stage2