---
- name: Template out version.tf
  template:
    src: terraform/version.tf.j2
    dest: "{{ tfile_dir }}/stage3/version.tf"

- name: Template out variables.tf
  template:
    src: terraform/vars.tf.j2
    dest: "{{ tfile_dir }}/stage3/vars.tf"

- name: Template out credentials.tf
  template:
    src: terraform/credentials.tf.j2
    dest: "{{ tfile_dir }}/stage3/credentials.tf"

- name: Template out data_ssh_key.tf
  template:
    src: terraform/stage2/data_ssh_key.tf.j2
    dest: "{{ tfile_dir }}/stage3/data_ssh_key.tf"

- name: Template out data_vpc.tf
  template:
    src: terraform/stage2/data_vpc.tf.j2
    dest: "{{ tfile_dir }}/stage3/data_vpc.tf"

- name: Template out data_subnets.tf
  template:
    src: terraform/stage2/data_subnets.tf.j2
    dest: "{{ tfile_dir }}/stage3/data_subnets.tf"

- name: Template out data_security_groups.tf
  template:
    src: terraform/stage2/data_security_groups.tf.j2
    dest: "{{ tfile_dir }}/stage3/data_security_groups.tf"

- name: Template out data_rhcos_image.tf
  template:
    src: terraform/stage2/data_rhcos_image.tf.j2
    dest: "{{ tfile_dir }}/stage3/data_rhcos_image.tf"

- name: Template out control_plane_nodes.tf
  template:
    src: terraform/stage3/control_plane_nodes.tf.j2
    dest: "{{ tfile_dir }}/stage3/control_plane_nodes.tf"

- name: Template out main.tf
  template:
    src: terraform/stage3/main.tf.j2
    dest: "{{ tfile_dir }}/stage3/main.tf"
