---
- name: Template out version.tf
  template:
    src: terraform/version.tf.j2
    dest: "{{ tfile_dir }}/stage1/version.tf"

- name: Template out variables.tf
  template:
    src: terraform/vars.tf.j2
    dest: "{{ tfile_dir }}/stage1/vars.tf"

- name: Template out credentials.tf
  template:
    src: terraform/credentials.tf.j2
    dest: "{{ tfile_dir }}/stage1/credentials.tf"

- name: Template out ssh_key.tf
  template:
    src: terraform/ssh_key.tf.j2
    dest: "{{ tfile_dir }}/stage1/ssh_key.tf"

- name: Template out vpc.tf
  template:
    src: terraform/stage1/vpc.tf.j2
    dest: "{{ tfile_dir }}/stage1/vpc.tf"

- name: Template out subnets.tf
  template:
    src: terraform/stage1/subnets.tf.j2
    dest: "{{ tfile_dir }}/stage1/subnets.tf"

- name: Template out security_groups.tf
  template:
    src: terraform/stage1/security_groups.tf.j2
    dest: "{{ tfile_dir }}/stage1/security_groups.tf"

- name: Template out rhcos_image.tf
  template:
    src: terraform/stage1/rhcos_image.tf.j2
    dest: "{{ tfile_dir }}/stage1/rhcos_image.tf"

- name: Template out Proctor Bastion Cloud Init Config
  template:
    src: terraform/cloud_inits/proctor_bastion.yaml.j2
    dest: "{{ tfile_dir }}/cloud_inits/proctor_bastion.yaml"

- name: Template out proctor_bastion.tf
  template:
    src: terraform/stage1/proctor_bastion.tf.j2
    dest: "{{ tfile_dir }}/stage1/proctor_bastion.tf"

- name: Template out Load Balancer Cloud Init Config
  template:
    src: terraform/cloud_inits/load_balancer.yaml.j2
    dest: "{{ tfile_dir }}/cloud_inits/load_balancer.yaml"

- name: Template out load_balancer.tf
  template:
    src: terraform/stage1/load_balancer.tf.j2
    dest: "{{ tfile_dir }}/stage1/load_balancer.tf"

- name: Template out DNS Cloud Init Config
  template:
    src: terraform/cloud_inits/dns_nodes.yaml.j2
    dest: "{{ tfile_dir }}/cloud_inits/dns_node{{ nodeNum }}.yaml"
  with_sequence: start=1 end="{{ number_of_dns_nodes }}" stride=1
  loop_control:
    loop_var: nodeNum

- name: Template out dns_nodes.tf
  template:
    src: terraform/stage1/dns_nodes.tf.j2
    dest: "{{ tfile_dir }}/stage1/dns_node{{ nodeNum }}.tf"
  with_sequence: start=1 end="{{ number_of_dns_nodes }}" stride=1
  loop_control:
    extended: yes
    loop_var: nodeNum

- name: Template out main.tf
  template:
    src: terraform/stage1/main.tf.j2
    dest: "{{ tfile_dir }}/stage1/main.tf"
