---
#- name: Install EPEL (EL8)
#  dnf:
#    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
#    state: present
#    disable_gpg_check: yes
#  when: ansible_distribution_major_version == '8'
#
#- name: Install EPEL (EL7)
#  yum:
#    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#    state: present
#    disable_gpg_check: yes
#  when: ansible_distribution_major_version == '7'

- name: Install base packages
  yum:
    name: "{{ base_packages }}"
    state: latest
