---
# defaults file for configureDNSNodes
update_system_packages: true
reboot_after_kernel_update: true

upstream_dns_servers:
  - 1.1.1.1
  - 1.0.0.1

## dns_systems must match the values set for `ansible_set_hostname` on the inventory
dns_systems:
  - name: "ns1-{{ workshop_shortcode }}-{{ guid }}"
  - name: "ns2-{{ workshop_shortcode }}-{{ guid }}"

knot_auth_dns: false
knot_resolving_dns: false

bind_dns: true

## BIND/NameD Default Config
bind_zones_path: /var/named/zones
bind_user: named
bind_group: named
bind_port: 53

## Knot DNS Default Config
knot_auth_dns_port: 54
knot_auth_dns_port_internal: 55
knot_resolving_dns_port: 53

knot_auth_dns_forward_resolver_fallback: false
knot_auth_dns_forward_resolver_fallback_servers:
  - remote_name: cloudflare
    dnsproxy_id: default
    address: 1.1.1.1
    port: 53

knot_user: knot
knot_group: knot

# knot_auth_dns_logging options: stdout, stderr, syslog, /path/to/file
knot_auth_dns_logging: syslog
# knot_auth_dns_logging_level options from least to most verbose: critical, error, warning, notice, info, debug
knot_auth_dns_logging_level: info

knot_auth_dns_default_zone_path: /var/lib/knot/zones

# knot_auth_dns_semantic_checks: off || on - Important: Wrap in quotes or else it will be interpreted as a boolean
knot_auth_dns_semantic_checks: "off"

knot_auth_dns_acl_notify_allow_cidr: 10.0.0.0/8
knot_auth_dns_acl_transfer_allow_cidr: 10.0.0.0/8
knot_auth_dns_acl_update_allow_cidr: 10.0.0.0/8

knot_auth_dns_tsigkey_name: tsigkey.
knot_auth_dns_tsigkey_path: /var/lib/knot/dns-tsigkey.yml

knot_resolving_dns_cache_size_mb: 1024

base_packages:
  - whois
  - bind-utils
  - nano
  - wget
  - curl
  - libedit
  - gnutls
  - lmdb-libs
  - userspace-rcu
  - libcap-ng
  - libcap-ng-utils
  - libnghttp2

generate_reverse_zones: true

cleanup_old_zone_backups: true
cleanup_old_zone_backups_older_than: 30d

default_zone_soa_params:
  refresh: 6h
  retry: 1h
  expire: 1w
  min_ttl: 600
