---
- name: Check for terraform.tfstate file
  stat:
    path: "{{ tfile_dir }}/terraform.tfstate"
  register: check_terraform_state

- name: Check for state of terraform.tfstate file lol
  shell:
    cmd: "wc -l {{ tfile_dir }}/terraform.tfstate | cut -d ' ' -f 1"
  when: check_terraform_state.stat.exists
  register: state_size_check

- name: Set fact for template recration
  set_fact:
    terraform_path: "{{ generation_directory }}/bin/terraform"

- name: Run Terraform destroy
  community.general.terraform:
    project_path: "{{ tfile_dir }}"
    state: absent
    binary_path: "{{ terraform_path }}"
    variables:
      ibmcloud_api_key: "{{ ibmcloud_api_key }}"
  when: check_terraform_state.stat.exists
  ignore_errors: yes
  register: terraform_result
  delay: 3
  retries: 3
  until: terraform_result is not failed
  tags:
    - run_terraform

- name: Remove old generated files
  file:
    path: "{{ tfile_dir }}"
    state: absent
  when: terraform_result.changed

- name: Run manual removal of assets
  block:
    - name: Get Student Load Balancer Floating IP assets
      ibm.cloudcollection.ibm_is_floating_ip_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-student-{{ item }}-lb-fip"
      register: student_lb_fip_info
      ignore_errors: true
      with_sequence: start=0 end="{{ student_count }}" stride=1

    - name: Release Student Load Balancer Floating IP
      uri:
        url: "{{ api_endpoint }}/v1/floating_ips/{{ item.resource.id }}?version=2021-01-12&generation=2"
        method: DELETE
        headers:
          Accept: application/json
          Authorization: "{{ ibm_api_token }}"
        return_content: yes
        status_code: [200, 204]
      register: lb_fip_api
      ignore_errors: yes
      failed_when: lb_fip_api.status == 404
      changed_when: lb_fip_api.status == 204
      when: item.resource.id is defined and (student_lb_fip_info|length>0)
      with_items: "{{ student_lb_fip_info.results }}"

    #- name: Release Student Load Balancer Floating IP
    #  ibm.cloudcollection.ibm_is_floating_ip:
    #    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    #    region: "{{ region }}"
    #    state: absent
    #    id: "{{ item.resource.id }}"
    #  when: item.resource.id is defined and (student_lb_fip_info|length>0)
    #  with_items: "{{ student_lb_fip_info.results }}"

    - name: Get Student Load Balancer VSI Information
      ibm.cloudcollection.ibm_is_instance_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-student-{{ item }}-lb-vsi"
        region: "{{ region }}"
      register: student_lb_vsi_info
      ignore_errors: true
      with_sequence: start=0 end="{{ student_count }}" stride=1

    - name: Remove Student Load Balancer VSIs
      uri:
        url: "{{ api_endpoint }}/v1/instances/{{ item.resource.id }}?version=2021-01-12&generation=2"
        method: DELETE
        headers:
          Accept: application/json
          Authorization: "{{ ibm_api_token }}"
        return_content: yes
        status_code: [200, 204]
      register: lb_vsi_api
      ignore_errors: yes
      failed_when: lb_vsi_api.status == 404
      changed_when: lb_vsi_api.status == 204
      when: item.resource.id is defined and (student_lb_vsi_info|length>0)
      with_items: "{{ student_lb_vsi_info.results }}"

    #- name: Remove Student Load Balancer VSIs
    #  ibm.cloudcollection.ibm_is_instance:
    #    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    #    state: absent
    #    id: "{{ item.resource.id }}"
    #    keys: []
    #  when: item.resource.id is defined and (student_lb_vsi_info|length>0)
    #  with_items: "{{ student_lb_vsi_info.results }}"

    - name: Dismantle student resources
      include_tasks: destroy_student_seats.yaml
      with_sequence: start=0 end="{{ student_count }}" stride=1
      loop_control:
        loop_var: student_num

    - name: Get Proctor Floating IP asset
      ibm.cloudcollection.ibm_is_floating_ip_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-pb-fip"
      register: pb_fip_info
      ignore_errors: true

    - name: Release Proctor Floating IP
      uri:
        url: "{{ api_endpoint }}/v1/floating_ips/{{ pb_fip_info.resource.id }}?version=2021-01-12&generation=2"
        method: DELETE
        headers:
          Accept: application/json
          Authorization: "{{ ibm_api_token }}"
        return_content: yes
        status_code: [200, 204]
      register: lb_fip_api
      ignore_errors: yes
      failed_when: lb_fip_api.status == 404
      changed_when: lb_fip_api.status == 204
      when: pb_fip_info.resource.id is defined

    #- name: Release Proctor Floating IP
    #  ibm.cloudcollection.ibm_is_floating_ip:
    #    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    #    region: "{{ region }}"
    #    state: absent
    #    id: "{{ pb_fip_info.resource.id }}"
    #  when: pb_fip_info.resource.id is defined

    - name: Get Proctor VSI Information
      ibm.cloudcollection.ibm_is_instance_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-pb-vsi"
        region: "{{ region }}"
      register: pb_vsi_info
      ignore_errors: true

    - name: Remove Proctor VSI
      uri:
        url: "{{ api_endpoint }}/v1/instances/{{ pb_vsi_info.resource.id }}?version=2021-01-12&generation=2"
        method: DELETE
        headers:
          Accept: application/json
          Authorization: "{{ ibm_api_token }}"
        return_content: yes
        status_code: [200, 204]
      register: pb_vsi_api
      ignore_errors: yes
      failed_when: >
        pb_vsi_api.status == 404
      changed_when: pb_vsi_api.status == 204

    - name: Get the SSH Key
      ibm.cloudcollection.ibm_is_ssh_key_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-ssh-key"
      register: ssh_key_output
      ignore_errors: true

    - name: Remove SSH Key
      ibm.cloudcollection.ibm_is_ssh_key:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        state: absent
        id: "{{ ssh_key_output.resource.id }}"
      when: ssh_key_output.resource.id is defined

    - name: Query Security Group for K8s Control Plane
      ibm.cloudcollection.ibm_is_security_group_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-control-plane-sg"
      register: k8s_control_plane_security_group
      ignore_errors: true

    - name: Remove Security Group for K8s Control Plane
      uri:
        url: "{{ api_endpoint }}/v1/security_groups/{{ k8s_control_plane_security_group.resource.id }}?version=2021-01-12&generation=2"
        method: DELETE
        headers:
          Accept: application/json
          Authorization: "{{ ibm_api_token }}"
        return_content: yes
        status_code: [200, 204]
      register: cp_sg_api
      ignore_errors: yes
      failed_when: >
        cp_sg_api.status == 403 or
        cp_sg_api.status == 404 or
        cp_sg_api.status == 409
      changed_when: cp_sg_api.status == 204
      when: k8s_control_plane_security_group.resource.id is defined

    #- name: Remove Security Group for K8s Control Plane
    #  ibm.cloudcollection.ibm_is_security_group:
    #    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    #    state: absent
    #    id: "{{ k8s_control_plane_security_group.resource.id }}"
    #  when: k8s_control_plane_security_group.resource.id is defined

    - name: Query Security Group for K8s App Nodes
      ibm.cloudcollection.ibm_is_security_group_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-app-node-sg"
      register: k8s_app_node_security_group
      ignore_errors: true

    - name: Remove Security Group for K8s App Nodes
      uri:
        url: "{{ api_endpoint }}/v1/security_groups/{{ k8s_app_node_security_group.resource.id }}?version=2021-01-12&generation=2"
        method: DELETE
        headers:
          Accept: application/json
          Authorization: "{{ ibm_api_token }}"
        return_content: yes
        status_code: [200, 204]
      register: app_sg_api
      ignore_errors: yes
      failed_when: >
        app_sg_api.status == 403 or
        app_sg_api.status == 404 or
        app_sg_api.status == 409
      changed_when: app_sg_api.status == 204
      when: k8s_app_node_security_group.resource.id is defined

    #- name: Remove Security Group for K8s App Nodes
    #  ibm.cloudcollection.ibm_is_security_group:
    #    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    #    state: absent
    #    id: "{{ k8s_app_node_security_group.resource.id }}"
    #  when: k8s_app_node_security_group.resource.id is defined

    - name: Query Security Group for Load Balancers
      ibm.cloudcollection.ibm_is_security_group_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-lb-sg"
      register: k8s_lb_security_group
      ignore_errors: true

    - name: Remove Security Group for Load Balancers
      uri:
        url: "{{ api_endpoint }}/v1/security_groups/{{ k8s_lb_security_group.resource.id }}?version=2021-01-12&generation=2"
        method: DELETE
        headers:
          Accept: application/json
          Authorization: "{{ ibm_api_token }}"
        return_content: yes
        status_code: [200, 204]
      register: lb_sg_api
      ignore_errors: yes
      failed_when: >
        lb_sg_api.status == 403 or
        lb_sg_api.status == 404 or
        lb_sg_api.status == 409
      changed_when: lb_sg_api.status == 204
      when: k8s_lb_security_group.resource.id is defined

    #- name: Remove Security Group for Load Balancers
    #  ibm.cloudcollection.ibm_is_security_group:
    #    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    #    state: absent
    #    id: "{{ k8s_lb_security_group.resource.id }}"
    #  when: k8s_lb_security_group.resource.id is defined

    - name: Query Security Group for Proctor Bastion
      ibm.cloudcollection.ibm_is_security_group_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-proctor-sg"
      register: proctor_bastion_security_group
      ignore_errors: true

    - name: Remove Security Group for Proctor Bastion
      uri:
        url: "{{ api_endpoint }}/v1/security_groups/{{ proctor_bastion_security_group.resource.id }}?version=2021-01-12&generation=2"
        method: DELETE
        headers:
          Accept: application/json
          Authorization: "{{ ibm_api_token }}"
        return_content: yes
        status_code: [200, 204]
      register: pb_sg_api
      ignore_errors: yes
      failed_when: >
        pb_sg_api.status == 403 or
        pb_sg_api.status == 404 or
        pb_sg_api.status == 409
      changed_when: pb_sg_api.status == 204
      when: proctor_bastion_security_group.resource.id is defined

    #- name: Remove Security Group for Proctor Bastion
    #  ibm.cloudcollection.ibm_is_security_group:
    #    ibmcloud_api_key: "{{ ibmcloud_api_key }}"
    #    state: absent
    #    id: "{{ proctor_bastion_security_group.resource.id }}"
    #  when: proctor_bastion_security_group.resource.id is defined

    - name: Get the VPC Subnet info
      ibm.cloudcollection.ibm_is_subnet_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-subnet"
      register: subnet_info
      ignore_errors: true

    - name: Remove VPC Subnet
      ibm.cloudcollection.ibm_is_subnet:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        state: absent
        id: "{{ subnet_info.resource.id }}"
      when: subnet_info.resource.id is defined

    - name: Get the VPC Public Gateway info
      ibm.cloudcollection.ibm_is_public_gateway_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-pubgtw"
      register: pubgtw_info
      ignore_errors: true

    - name: Remove the VPC Public Gateway
      ibm.cloudcollection.ibm_is_public_gateway:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        state: absent
        id: "{{ pubgtw_info.resource.id }}"
      when: pubgtw_info.resource.id is defined

    - name: Get the VPC details
      ibm.cloudcollection.ibm_is_vpc_info:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        name: "{{ workshop_shortcode }}-{{ guid }}-vpc"
      register: vpc_output
      ignore_errors: true

    - name: Remove VPC
      ibm.cloudcollection.ibm_is_vpc:
        ibmcloud_api_key: "{{ ibmcloud_api_key }}"
        region: "{{ region }}"
        state: absent
        id: "{{ vpc_output.resource.id }}"
      when: vpc_output.resource.id is defined
  when: not check_terraform_state.stat.exists|bool